Add initial xrefsect support
michaeljones/breathe pull request #589
Opened 2020-10-09 01:01 UTC by utzig

Add basic parsing support and rendering of xrefsect blocks. The current implementation does not generate links or any pages.

An xrefsect is generated when a @xrefitem keyword is found in Doxygen documentation, as well as the specialized forms like `\bug`, `\test` and `\deprecated`.

https://www.doxygen.nl/manual/commands.html#cmdxrefitem

2020-10-09 01:03 UTC, utzig commented
For an example, this source:

```
/**
 * This is just some non-useful text.
 *
 * @xrefitem examples "Examples" "Examples" "Some xrefitem example"
 *
 * @bug Super buggy function
 */
void some_xref_fn(void);

/**
 * More non-useful text.
 *
 * @xrefitem examples "Examples" "Examples" "Some xrefitem example"
 *
 * @deprecated Don't use this
 */
void another_xref_fn(void);
```

Will render like this:

![xrefitem](https://user-images.githubusercontent.com/107070/95529709-05bc7e80-09b2-11eb-87ec-fc1fd44beadd.jpg)

2020-10-09 15:17 UTC, vermeeren requested changes
Diff itself is good, but could you add the documentation example to the doc? I'm thinking somewhere on `documentation/source/specific.rst` is good. Probably with a title like `Doxygen xrefsect`. Thanks!

2020-10-19 11:04 UTC, utzig commented
> @utzig Diff itself is good, but could you add the documentation example to the doc? I'm thinking somewhere on `documentation/source/specific.rst` is good. Probably with a title like `Doxygen xrefsect`. Thanks!

Done.

2020-10-20 15:12 UTC, vermeeren approved these changes
@utzig Thanks, much appreciated!

2020-10-20 15:12 UTC, merged

2020-10-20 15:36 UTC, vermeeren commented
@utzig Released as v4.23.0.