Add support for xrefitem based page generation
michaeljones/breathe pull request #596
Opened 2020-11-05 15:10 UTC by utzig

Implement full support for parsing XML using xrefitem, and page blocks. Add a new directive, "doxygenpage", for rendering pages that contain data that was "xrefitem"'d.

For the "doxygenpage" directive, which uses a block of kind="page", which is pretty much the same as kind="namespace" or kind="group", I decided to remove most options, but I might want "content-only" later which I'd rather add in a followup PR.

A bit of confusion might exist now that I am calling this "doxygenpage" and using examples from "xrefsect" while building the examples, which is due to the strong relation between both, but maybe the "xrefsect" example should now be renamed "page".

I am adding a very small test attached that can be built using `doxygen doxyfile && sphinx-build -b html . html` just in case you want to see how the results look: [xref_test.tar.gz](https://github.com/michaeljones/breathe/files/5495202/xref_test.tar.gz)

Also includes commits fixing a few issues found during the way.

PR: tests are failing on Sphinx==3.3.0 on my machine (but this is also the case for `master`).

2020-11-05 15:16 UTC, utzig commented
@vermeeren breathe `master` seems to also fail for `https://github.com/sphinx-doc/sphinx.git@3.2.x`. Can I disable it temporarily on this PR? I believe the issue is with Sphinx itself, and also happens with 3.3.0 release; I have already submitted a fix upstream a few days ago...

2020-11-05 15:18 UTC, vermeeren commented
@utzig Yeah no problem, you can disable it for now.

2020-11-05 15:20 UTC, utzig commented
> @utzig Yeah no problem, you can disable it for now.

Ooops, sorry, did not expect you to answer this fast! I did it now, but I'll drop the commit once the test passes (if it does!).

2020-11-05 19:13 UTC, utzig commented
> @utzig Yeah no problem, you can disable it for now.

I dropped the commit disabling Sphinx git and >3.2.1 so it should fail again!

2020-11-05 21:12 UTC, utzig commented
Can rebase after #597 to pass again...

2020-11-15 16:20 UTC, vermeeren requested changes
@utzig Finally had some proper time to review today, sorry for the delay. The directive itself, including implementation, are all good. This definitely fills in a gap of functionality, big thanks for that.

Just noticed some minor issues with the docs, can you fixup? The follow-up review will be quick and a release will be made after merging as usual.

2020-11-15 16:20 UTC, vermeeren commented on documentation/source/page.rst
> +page. A doxygen page is created for each "key" of every \xrefitem command used
Here too need either `\\` or ``` ``\xrefitem`` ```.

2020-11-15 22:35 UTC, utzig commented on documentation/source/directives.rst
> +and to see it in action.
This was a copypasta from doxygroup so I just changed to `:ref:doxygenpage documentation ...`

2020-11-15 22:35 UTC, utzig commented
@vermeeren I believe all issues were fixed.

2020-11-15 22:37 UTC, vermeeren commented on documentation/source/directives.rst
> +and to see it in action.
Yeah figured something like that was the case.

2020-11-15 22:58 UTC, merged

2020-11-15 23:00 UTC, vermeeren reviewed
@utzig Everything is good, thanks! Compliments for the clean commits as usual. Released as v4.24.0.